packages:
  - packages/*
  - docs
  - test
  - test/*
  - scripts/*
  - examples/*
  - playground/*

engineStrict: true

onlyBuiltDependencies:
  - '@mui/internal-babel-plugin-display-name'
  - '@vvago/vale'
  - core-js
  - esbuild
  - nx
  - sharp
  - unrs-resolver
patchedDependencies:
  '@mui/internal-docs-infra@0.10.1-canary.3': patches/@mui__internal-docs-infra@0.10.1-canary.3.patch
